# DATA
dataset: mnist
dataroot: /home/jason/data
img_size: 32

# MODEL
dim: 64
n_stages: 4
total_steps: 200
beta_schedule_mode: linear

# TRAIN
epochs: 50
batch_size: 256

optimizer:
  choice: adam
  adam:
    lr: 0.0005

sample_freq: 1
save_freq: 5
