data:
  target: datasets.celebahq.CelebAHQ
  params:
    root: ~/data/CelebA-HQ/
    img_size: 256
  img_channels: 3

model:
  target: models.unet.UNet
  params:
    in_channels: 3
    out_channels: 3
    dim: 128
    dim_mults: [1, 1, 2, 2, 4, 4]
    use_attn: [false, false, false, false, true, false]
    num_res_blocks: 2
    n_heads: 1
    dropout: 0.0

diffusion:
  target: diffusions.ddpm.DDPM
  params:
    total_steps: 1000
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    objective: pred_eps
    var_type: fixed_small
