seed: 2022

data:
  target: datasets.celebahq.CelebAHQ
  params:
    root: ~/data/CelebA-HQ/
    img_size: 256
  img_channels: 3

dataloader:
  num_workers: 4
  pin_memory: true
  prefetch_factor: 2

model:
  target: models.pesser.model.Model
  params:
    resolution: 256
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 1, 2, 2, 4, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    resamp_with_conv: true

diffusion:
  target: diffusions.ddpm.DDPM
  params:
    total_steps: 1000
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    objective: pred_eps
    var_type: fixed_small
