type: openai/guided_diffusion/unet
image_size: 256
in_channels: 3
model_channels: 256
out_channels: 6
num_res_blocks: 2
attention_resolutions: [32, 16, 8]
dropout: 0.0
channel_mult: [1, 1, 2, 2, 4, 4]
conv_resample: true
dims: 2
num_classes: ~
use_checkpoint: false
use_fp16: false
num_heads: 4
num_head_channels: 64
num_heads_upsample: -1
use_scale_shift_norm: true
resblock_updown: true
use_new_attention_order: false
