SEED: 2022

DATA:
  NAME: CIFAR-10
  DATAROOT: /data/CIFAR-10/
  IMG_SIZE: 32
  IMG_CHANNELS: 3
  NUM_CLASSES: 10


DATALOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
  PREFETCH_FACTOR: 2
  BATCH_SIZE: 128
  MICRO_BATCH: 0


MODEL:
  TYPE: unet_cond
  DIM: 128
  DIM_MULTS: [1, 2, 2, 2]
  USE_ATTN: [false, true, true, false]
  NUM_RES_BLOCKS: 2
  RESBLOCK_GROUPS: 32
  ATTN_GROUPS: 32
  ATTN_HEAD_DIMS: 64
  RESBLOCK_UPDOWN: true
  DROPOUT: 0.1
  EMA_DECAY: 0.9999
  WEIGHTS: ~


CLASSIFIER_FREE:
  TOTAL_STEPS: 1000
  BETA_SCHEDULE: cosine
  BETA_START: 0.0001
  BETA_END: 0.02
  OBJECTIVE: pred_eps
  VAR_TYPE: fixed_large


TRAIN:
  TRAIN_STEPS: 800000
  RESUME: ~
  PRINT_FREQ: 200
  SAMPLE_FREQ: 1000
  SAVE_FREQ: 10000

  P_UNCOND: 0.2

  OPTIM:
    TYPE: AdamW
    LR: 0.0002
