data:
  dataset: CIFAR-10
  dataroot: /data/CIFAR-10/
  img_size: 32
  img_channels: 3
  num_classes: 10


model:
  dim: 128
  dim_mults: [1, 2, 2, 2]
  use_attn: [false, true, true, false]
  num_res_blocks: 2
  resblock_groups: 32
  attn_groups: 32
  attn_head_dims: 64
  resblock_updown: true
  dropout: 0.1
  ema_decay: 0.9999


classifier_free:
  total_steps: 1000
  beta_schedule: cosine
  beta_start: 0.0001
  beta_end: 0.02
  objective: pred_eps
  var_type: fixed_large


train:
  epochs: 2050
  batch_size: 128
  n_samples_each_class: 16
  guidance_scale: 1.0

  p_uncond: 0.2

  pretrained: ~
  resume: ~

  optimizer:
    type: adamw
    lr: 0.0002

  print_freq: { by_step: 300 }
  sample_freq: { by_epoch: 10 }
  save_freq: { by_epoch: 50 }


sample:
  model_path: ./runs/classifier-free-cifar10/ckpt/epoch1799.pt
  load_ema: true
  n_samples_each_class: 8
  guidance_scale: 1.0
  batch_size: 8
  save_dir: ./samples/classifier-free-cifar10/scale1/

  use_ddim: false
  ddim:
    eta: 0.
    skip_type: linear
    skip_steps: 100
