data:
  dataset: CIFAR-10
  dataroot: /data/CIFAR-10/
  img_size: 32


model:
  # UNet
  dim: 128
  dim_mults: [1, 2, 2, 2]
  use_attn: [false, true, false, false]
  num_res_blocks: 2
  resblock_groups: 32
  attn_groups: 32
  attn_heads: 1
  dropout: 0.1
  ema_decay: 0.9999

  # DDPM
  total_steps: 1000
  beta_schedule: linear
  beta_start: 0.0001
  beta_end: 0.02
  objective: pred_eps
  var_type: fixed_large


train:
  epochs: 2050
  batch_size: 128
  n_samples: 64

  pretrained: ~
  resume: ~

  optimizer:
    type: adam
    lr: 0.0002

  use_tensorboard: true
  print_freq: { by_step: 300 }
  sample_freq: { by_epoch: 10 }
  save_freq: { by_epoch: 50 }


test:
  pretrained: ./runs/ddpm-cifar10/model.pt
  load_ema: true

  evaluate:
    num_real: 50000
    generated_samples: ./samples/ddpm-cifar10/random/

  sample:
    n_samples: 64
    batch_size: 64
    save_dir: ./samples/ddpm-cifar10/random/

  sample_denoise:
    n_samples: 8
    batch_size: 8
    return_freq: 50
    save_dir: ./samples/ddpm-cifar10/denoise/
