# DATA
dataset: celeba-hq
dataroot: /home/jason/data/celeba-hq/CelebA-HQ-img
img_size: 128

# MODEL
dim: 128
dim_mults: [1, 1, 2, 2, 4, 4]
total_steps: 1000
beta_schedule_mode: linear

# TRAIN
epochs: 500
batch_size: 64

optimizer:
  choice: adam
  adam:
    lr: 0.00005

sample_freq: 1
save_freq: 25
