SEED: 2001

DATA:
  NAME: CIFAR-10
  DATAROOT: /data/CIFAR-10/
  IMG_SIZE: 32
  IMG_CHANNELS: 3


MODEL:
  TYPE: unet
  DIM: 128
  DIM_MULTS: [1, 2, 2, 2]
  USE_ATTN: [false, true, false, false]
  NUM_RES_BLOCKS: 2
  RESBLOCK_GROUPS: 32
  ATTN_GROUPS: 32
  ATTN_HEADS: 1
  DROPOUT: 0.1
  EMA_DECAY: 0.9999
  WEIGHTS: ~


DDIM:
  TOTAL_STEPS: 1000
  BETA_SCHEDULE: linear
  BETA_START: 0.0001
  BETA_END: 0.02
  OBJECTIVE: pred_eps
  ETA: 0.0
