data:
  dataset: CelebA-HQ
  dataroot: /data/CelebA-HQ/
  img_size: 256
  img_channels: 3


model:
  dim: 128
  dim_mults: [1, 1, 2, 2, 4, 4]
  use_attn: [false, false, false, false, true, false]
  num_res_blocks: 2
  resblock_groups: 32
  attn_groups: 32
  attn_heads: 1
  dropout: 0.1
  ema_decay: 0.9999


ddim:
  total_steps: 1000
  beta_schedule: linear
  beta_start: 0.0001
  beta_end: 0.02
  objective: pred_eps
  eta: 0.
  skip_type: uniform
  skip_steps: 100


sample:
  model_path: ./runs/ddpm-celebahq-resume2/ckpt/epoch409.pt
  load_ema: true
  n_samples: 64
  batch_size: 16
  save_dir: ./samples/ddim-celebahq/random-100steps/


sample_interpolate:
  model_path: ./runs/ddpm-celebahq-resume2/ckpt/epoch409.pt
  load_ema: true
  n_samples: 16
  n_interpolate: 10
  batch_size: 16
  save_dir: ./samples/ddim-celebahq/interpolate-100steps/
