seed: 2022

data:
  target: datasets.celebahq.CelebAHQ
  params:
    root: ~/data/CelebA-HQ/
    img_size: 256
  img_channels: 3

dataloader:
  num_workers: 4
  pin_memory: true
  prefetch_factor: 2

model:
  target: models.unet.UNet
  params:
    in_channels: 3
    out_channels: 3
    dim: 128
    dim_mults: [1, 1, 2, 2, 4, 4]
    use_attn: [false, false, false, false, true, false]
    num_res_blocks: 2
    n_heads: 1
    dropout: 0.0

diffusion:
  target: diffusions.ddpm.DDPM
  params:
    total_steps: 1000
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    objective: pred_eps
    var_type: fixed_small

train:
  n_steps: 500000
  batch_size: 64
  micro_batch: 0

  clip_grad_norm: 1.0
  ema_decay: 0.9999
  ema_gradual: true

  print_freq: 400
  save_freq: 10000
  sample_freq: 5000
  n_samples: 36

  optim:
    target: torch.optim.Adam
    params:
      lr: 0.00002
