data:
  dataset: CelebA-HQ
  dataroot: /data/CelebA-HQ/
  img_size: 256
  img_channels: 3


model:
  # UNet
  dim: 128
  dim_mults: [1, 1, 2, 2, 4, 4]
  use_attn: [false, false, false, false, true, false]
  num_res_blocks: 2
  resblock_groups: 32
  attn_groups: 32
  attn_heads: 1
  dropout: 0.0
  ema_decay: 0.9999

  # DDPM
  total_steps: 1000
  beta_schedule: linear
  beta_start: 0.0001
  beta_end: 0.02
  objective: pred_eps
  var_type: fixed_small


train:
  epochs: 500
  batch_size: 32
  n_samples: 36

  pretrained: ~
  resume: ~

  optimizer:
    type: adam
    lr: 0.00002

  print_freq: { by_step: 300 }
  sample_freq: { by_epoch: 10 }
  save_freq: { by_epoch: 10 }


sample:
  model_path: ./runs/ddpm-celebahq-resume2/ckpt/epoch409.pt
  load_ema: true
  n_samples: 64
  batch_size: 16
  save_dir: ./samples/ddpm-celebahq/random/


sample_denoise:
  model_path: ./runs/ddpm-celebahq-resume2/ckpt/epoch409.pt
  load_ema: true
  n_samples: 8
  batch_size: 8
  n_denoise: 20
  save_dir: ./samples/ddpm-celebahq/denoise/


sample_progressive:
  model_path: ./runs/ddpm-celebahq-resume2/ckpt/epoch409.pt
  load_ema: true
  n_samples: 8
  batch_size: 8
  n_progressive: 20
  save_dir: ./samples/ddpm-celebahq/progressive/


evaluate:
  num_real: 10000
  generated_samples: ./samples/ddpm-celebahq/random/
