SEED: 2022

DATA:
  NAME: MNIST
  DATAROOT: /data/MNIST/
  IMG_SIZE: 32
  IMG_CHANNELS: 1


DATALOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
  PREFETCH_FACTOR: 2
  BATCH_SIZE: 128
  MICRO_BATCH: 0


MODEL:
  TYPE: unet
  DIM: 64
  DIM_MULTS: [1, 2, 2, 2]
  USE_ATTN: [false, true, false, false]
  NUM_RES_BLOCKS: 2
  RESBLOCK_GROUPS: 32
  ATTN_GROUPS: 32
  ATTN_HEADS: 1
  DROPOUT: 0.1
  EMA_DECAY: 0.9999
  WEIGHTS: ~


DDPM:
  TOTAL_STEPS: 200
  BETA_SCHEDULE: linear
  BETA_START: 0.0001
  BETA_END: 0.02
  OBJECTIVE: pred_eps
  VAR_TYPE: fixed_small


TRAIN:
  TRAIN_STEPS: 80000
  RESUME: ~
  PRINT_FREQ: 200
  SAMPLE_FREQ: 1000
  SAVE_FREQ: 10000

  OPTIM:
    TYPE: Adam
    LR: 0.0002
