data:
  target: datasets.lsun.LSUN
  params:
    dataroot: ~/data/LSUN
    label: church
    img_size: 256
  img_channels: 3

model:
  target: models.pesser.model.Model
  params:
    resolution: 256
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 1, 2, 2, 4, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    resamp_with_conv: true

diffusion:
  target: diffusions.ddpm.DDPM
  params:
    total_steps: 1000
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    objective: pred_eps
    var_type: fixed_small
